name: update-cloud-providers

jobs:
  update-information:
    if: (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: "Set AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.DV_EXPLORE_AWS_REGION }}
          aws-access-key-id: ${{ secrets.DV_EXPLORE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DV_EXPLORE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Upload cloud provider file to S3
        run: |
          aws s3 cp skyline-vscode/react-ui/src/schema/providers.json s3://deepview-explorer-public/vscode-cloud-providers/