name: update-cloud-providers

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths:
      - 'deepview-explore/react-ui/public/providers.json'

jobs:
  update-information:
    if: (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: "Set AWS credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.DV_EXPLORE_AWS_REGION }}
          aws-access-key-id: ${{ secrets.DV_EXPLORE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DV_EXPLORE_AWS_SECRET_ACCESS_KEY }}

      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Upload cloud provider file to S3
        run: |
          aws s3 cp deepview-explore/react-ui/public/providers.json s3://deepview-explorer-public/vscode-cloud-providers/
          aws s3api put-object-acl --bucket deepview-explorer-public --key vscode-cloud-providers/providers.json --acl public-read